### PR TITLE
Initial commit

### PR DESCRIPTION
**Pull request by jmorra**
This is the initial code.  It's still lacking unit tests, but they will be added later.

---

This change is [Reviewable](https://reviewable.io/reviews/eharmony/spotz/1)

### CODE REVIEW

**Comment by jmorra** [comment]
Reviewed 12 of 22 files at r1, 2 of 2 files at r3, 10 of 10 files at r4.
Review status: all files reviewed at latest revision, 18 unresolved discussions.

---

_[pom.xml, line 46 [r4]](https://reviewable.io:443/reviews/eharmony/spotz/1#-KEc7JjeQCJ1D2G9iITq:-KEc7JjeQCJ1D2G9iITr:1390124141) ([raw file](https://github.com/eharmony/spotz/blob/4e3806ec8c4f9f7dd80922635d58784558b44009/pom.xml#L46)):_
Why do we need the compiler and reflect?

---

_[src/main/scala/com/eharmony/spotz/Preamble.scala, line 12 [r4]](https://reviewable.io:443/reviews/eharmony/spotz/1#-KEc7h-7sWIuate7r_N8:-KEc7h-8E_U8Qb-IUYdp:994219616) ([raw file](https://github.com/eharmony/spotz/blob/4e3806ec8c4f9f7dd80922635d58784558b44009/src/main/scala/com/eharmony/spotz/Preamble.scala#L12)):_
Isn't this the default compare implementation for Double?

---

_[src/main/scala/com/eharmony/spotz/examples/branin/BraninMaxTrials.scala, line 13 [r4]](https://reviewable.io:443/reviews/eharmony/spotz/1#-KEcAeL1_nJMRQ8K3Emn:-KEcAeL2kT-kXeNmiMzU:-1540204320) ([raw file](https://github.com/eharmony/spotz/blob/4e3806ec8c4f9f7dd80922635d58784558b44009/src/main/scala/com/eharmony/spotz/examples/branin/BraninMaxTrials.scala#L13)):_
Can you add a comment about what this is and a preferably a link too?

---

_[src/main/scala/com/eharmony/spotz/examples/branin/BraninMaxTrials.scala, line 27 [r4]](https://reviewable.io:443/reviews/eharmony/spotz/1#-KEcAlLltua4QsEH8sWx:-KEcAlLltua4QsEH8sWy:-642223124) ([raw file](https://github.com/eharmony/spotz/blob/4e3806ec8c4f9f7dd80922635d58784558b44009/src/main/scala/com/eharmony/spotz/examples/branin/BraninMaxTrials.scala#L27)):_
Can you add at least a little bit of CLI parsing so we can see what the arguments are from the command line.

---

_[src/main/scala/com/eharmony/spotz/examples/branin/BraninObjective.scala, line 9 [r4]](https://reviewable.io:443/reviews/eharmony/spotz/1#-KEcAvkoOHp2KItZ9TED:-KEcAvkoOHp2KItZ9TEE:1700983563) ([raw file](https://github.com/eharmony/spotz/blob/4e3806ec8c4f9f7dd80922635d58784558b44009/src/main/scala/com/eharmony/spotz/examples/branin/BraninObjective.scala#L9)):_
Where did these numbers come from?

---

_[src/main/scala/com/eharmony/spotz/examples/branin/BraninTimed.scala, line 29 [r4]](https://reviewable.io:443/reviews/eharmony/spotz/1#-KEcAzM4QIkWG10_IX4Y:-KEcAzM4QIkWG10_IX4Z:-2105446550) ([raw file](https://github.com/eharmony/spotz/blob/4e3806ec8c4f9f7dd80922635d58784558b44009/src/main/scala/com/eharmony/spotz/examples/branin/BraninTimed.scala#L29)):_
This looks very similar to the other main function, maybe coalesce.

---

_[src/main/scala/com/eharmony/spotz/examples/vw/SparkVwCrossValidation.scala, line 16 [r4]](https://reviewable.io:443/reviews/eharmony/spotz/1#-KEcJtq3MdkQuMTWcte-:-KEcJtq3MdkQuMTWcte0:-2068376018) ([raw file](https://github.com/eharmony/spotz/blob/4e3806ec8c4f9f7dd80922635d58784558b44009/src/main/scala/com/eharmony/spotz/examples/vw/SparkVwCrossValidation.scala#L16)):_
Is this designed for testing or some user purpose?  I think this needs a formal CLI.

---

_[src/main/scala/com/eharmony/spotz/examples/vw/SparkVwCrossValidation.scala, line 29 [r4]](https://reviewable.io:443/reviews/eharmony/spotz/1#-KEcJzUrioawjTXX85mf:-KEcJzUrioawjTXX85mg:-112605245) ([raw file](https://github.com/eharmony/spotz/blob/4e3806ec8c4f9f7dd80922635d58784558b44009/src/main/scala/com/eharmony/spotz/examples/vw/SparkVwCrossValidation.scala#L29)):_
Where do these numbers come from?

---

_[src/main/scala/com/eharmony/spotz/objective/vw/SparkVwCrossValidationObjective.scala, line 46 [r4]](https://reviewable.io:443/reviews/eharmony/spotz/1#-KEcKOxS2VmnCHH04ni8:-KEcKOxS2VmnCHH04ni9:806967826) ([raw file](https://github.com/eharmony/spotz/blob/4e3806ec8c4f9f7dd80922635d58784558b44009/src/main/scala/com/eharmony/spotz/objective/vw/SparkVwCrossValidationObjective.scala#L46)):_
This leaves the Source open.  It should be closed.

---

_[src/main/scala/com/eharmony/spotz/objective/vw/SparkVwCrossValidationObjective.scala, line 50 [r4]](https://reviewable.io:443/reviews/eharmony/spotz/1#-KEcStbMTpO9KghCqMPb:-KEcStbMTpO9KghCqMPc:1982188435) ([raw file](https://github.com/eharmony/spotz/blob/4e3806ec8c4f9f7dd80922635d58784558b44009/src/main/scala/com/eharmony/spotz/objective/vw/SparkVwCrossValidationObjective.scala#L50)):_
Can this be done better using `groupBy`?

---

_[src/main/scala/com/eharmony/spotz/objective/vw/SparkVwCrossValidationObjective.scala, line 58 [r4]](https://reviewable.io:443/reviews/eharmony/spotz/1#-KEcTXl-0e1b5ZHueCMZ:-KEcTXl-0e1b5ZHueCM_:600830136) ([raw file](https://github.com/eharmony/spotz/blob/4e3806ec8c4f9f7dd80922635d58784558b44009/src/main/scala/com/eharmony/spotz/objective/vw/SparkVwCrossValidationObjective.scala#L58)):_
It seems like the code for this and testing is very similar, should this be a separate function?

---

_[src/main/scala/com/eharmony/spotz/objective/vw/SparkVwCrossValidationObjective.scala, line 108 [r4]](https://reviewable.io:443/reviews/eharmony/spotz/1#-KEcTrsXAbPAjq3-bg_e:-KEcTrsXAbPAjq3-bg_f:80759348) ([raw file](https://github.com/eharmony/spotz/blob/4e3806ec8c4f9f7dd80922635d58784558b44009/src/main/scala/com/eharmony/spotz/objective/vw/SparkVwCrossValidationObjective.scala#L108)):_
I assume in the future you will support a lot more options than just l?

---

_[src/main/scala/com/eharmony/spotz/objective/vw/VwProcess.scala, line 54 [r4]](https://reviewable.io:443/reviews/eharmony/spotz/1#-KEcU4d269pTRvIULo5h:-KEcU4d269pTRvIULo5i:-1140671149) ([raw file](https://github.com/eharmony/spotz/blob/4e3806ec8c4f9f7dd80922635d58784558b44009/src/main/scala/com/eharmony/spotz/objective/vw/VwProcess.scala#L54)):_
This is really nice I like this a lot.

---

_[src/main/scala/com/eharmony/spotz/optimizer/package.scala, line 4 [r4]](https://reviewable.io:443/reviews/eharmony/spotz/1#-KEcUFaJrT9As4cGjG_1:-KEcUFaJrT9As4cGjG_2:1143630169) ([raw file](https://github.com/eharmony/spotz/blob/4e3806ec8c4f9f7dd80922635d58784558b44009/src/main/scala/com/eharmony/spotz/optimizer/package.scala#L4)):_
Why is this necessary?

---

_[src/main/scala/com/eharmony/spotz/optimizer/RandomSearch.scala, line 27 [r4]](https://reviewable.io:443/reviews/eharmony/spotz/1#-KEcULg2ARrE1Ti_gChK:-KEcULg38aMH0LplrVia:1290445632) ([raw file](https://github.com/eharmony/spotz/blob/4e3806ec8c4f9f7dd80922635d58784558b44009/src/main/scala/com/eharmony/spotz/optimizer/RandomSearch.scala#L27)):_
I think you should expose this as a parameter even it has a default value in the constructor.

---

_[src/main/scala/com/eharmony/spotz/optimizer/framework/SparkFramework.scala, line 51 [r4]](https://reviewable.io:443/reviews/eharmony/spotz/1#-KEcUnNttpw3Ur7OVvwi:-KEcUnNttpw3Ur7OVvwj:1551796944) ([raw file](https://github.com/eharmony/spotz/blob/4e3806ec8c4f9f7dd80922635d58784558b44009/src/main/scala/com/eharmony/spotz/optimizer/framework/SparkFramework.scala#L51)):_
@deakator, I know that you had some ideas about hashing here.

---

_[src/main/scala/com/eharmony/spotz/optimizer/stop/StopStrategy.scala, line 5 [r4]](https://reviewable.io:443/reviews/eharmony/spotz/1#-KEcV01lIxwp3vWj8eIJ:-KEcV01lIxwp3vWj8eIK:365582357) ([raw file](https://github.com/eharmony/spotz/blob/4e3806ec8c4f9f7dd80922635d58784558b44009/src/main/scala/com/eharmony/spotz/optimizer/stop/StopStrategy.scala#L5)):_
This is really nice, add some comments here about these two strategies.

---

_[src/main/scala/com/eharmony/spotz/util/RegexUtil.scala, line 6 [r4]](https://reviewable.io:443/reviews/eharmony/spotz/1#-KEcVLI319HsvbaAJDtQ:-KEcVLI319HsvbaAJDtR:1231043768) ([raw file](https://github.com/eharmony/spotz/blob/4e3806ec8c4f9f7dd80922635d58784558b44009/src/main/scala/com/eharmony/spotz/util/RegexUtil.scala#L6)):_
Is it worthwhile to put the VW loss regex here too?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/eharmony/spotz/1)_

**Comment by vsuthichai** [comment]
Reviewed 13 of 32 files at r5.
Review status: 20 of 34 files reviewed at latest revision, 16 unresolved discussions.

---

_[a discussion](https://reviewable.io:443/reviews/eharmony/spotz/1#-KD1F_pRY0s7FKLZTy64:-KD1F_pS1T8n2bxV26nv:-629826719) (no related file):_
Add unit tests

---

_[pom.xml, line 46 [r4]](https://reviewable.io:443/reviews/eharmony/spotz/1#-KEc7JjeQCJ1D2G9iITq:-KLz9Ia3zKvL_F9im7VQ:-639974882) ([raw file](https://github.com/eharmony/spotz/blob/4e3806ec8c4f9f7dd80922635d58784558b44009/pom.xml#L46)):_
<details><summary>

<i>Previously, jmorra (Jon Morra) wrote…</i></summary>



> Why do we need the compiler and reflect?
> </details>
> They are brought in as transitive dependencies from other libraries.  However their version does not reflect ${scala.version} as defined in properties.  I'm declaring it to force it to be the same version of scala as defined in the properties.

---

_[src/main/scala/com/eharmony/spotz/Preamble.scala, line 12 [r4]](https://reviewable.io:443/reviews/eharmony/spotz/1#-KEc7h-7sWIuate7r_N8:-KLzJqGVUXP6kP4FET66:-380808958) ([raw file](https://github.com/eharmony/spotz/blob/4e3806ec8c4f9f7dd80922635d58784558b44009/src/main/scala/com/eharmony/spotz/Preamble.scala#L12)):_
<details><summary>

<i>Previously, jmorra (Jon Morra) wrote…</i></summary>



> Isn't this the default compare implementation for Double?
> </details>
> This is the default Point, Loss tuple ordering.

---

_[src/main/scala/com/eharmony/spotz/examples/branin/BraninMaxTrials.scala, line 13 [r4]](https://reviewable.io:443/reviews/eharmony/spotz/1#-KEcAeL1_nJMRQ8K3Emn:-KLzMN5NlMIEPHdoxYT6:1481713219) ([raw file](https://github.com/eharmony/spotz/blob/4e3806ec8c4f9f7dd80922635d58784558b44009/src/main/scala/com/eharmony/spotz/examples/branin/BraninMaxTrials.scala#L13)):_
<details><summary>

<i>Previously, jmorra (Jon Morra) wrote…</i></summary>



> Can you add a comment about what this is and a preferably a link too?
> </details>
> Yes, will do

---

_[src/main/scala/com/eharmony/spotz/examples/branin/BraninMaxTrials.scala, line 27 [r4]](https://reviewable.io:443/reviews/eharmony/spotz/1#-KEcAlLltua4QsEH8sWx:-KLzMPe6ziN1iNGXoQf9:160394146) ([raw file](https://github.com/eharmony/spotz/blob/4e3806ec8c4f9f7dd80922635d58784558b44009/src/main/scala/com/eharmony/spotz/examples/branin/BraninMaxTrials.scala#L27)):_
<details><summary>

<i>Previously, jmorra (Jon Morra) wrote…</i></summary>



> Can you add at least a little bit of CLI parsing so we can see what the arguments are from the command line.
> </details>
> Yes

---

_[src/main/scala/com/eharmony/spotz/examples/branin/BraninObjective.scala, line 9 [r4]](https://reviewable.io:443/reviews/eharmony/spotz/1#-KEcAvkoOHp2KItZ9TED:-KLzJGGf6NGoRebLjzQP:-155147889) ([raw file](https://github.com/eharmony/spotz/blob/4e3806ec8c4f9f7dd80922635d58784558b44009/src/main/scala/com/eharmony/spotz/examples/branin/BraninObjective.scala#L9)):_
<details><summary>

<i>Previously, jmorra (Jon Morra) wrote…</i></summary>



> Where did these numbers come from?
> </details>
> They are part of the Branin Function.  Will include a link to the page describing the function.

---

_[src/main/scala/com/eharmony/spotz/examples/vw/SparkVwCrossValidation.scala, line 16 [r4]](https://reviewable.io:443/reviews/eharmony/spotz/1#-KEcJtq3MdkQuMTWcte-:-KLzERSga11jUL_4-ct_:-1556559566) ([raw file](https://github.com/eharmony/spotz/blob/4e3806ec8c4f9f7dd80922635d58784558b44009/src/main/scala/com/eharmony/spotz/examples/vw/SparkVwCrossValidation.scala#L16)):_
<details><summary>

<i>Previously, jmorra (Jon Morra) wrote…</i></summary>



> Is this designed for testing or some user purpose?  I think this needs a formal CLI.
> </details>
> It's an example and something I used as a test while developing the framework.

---

_[src/main/scala/com/eharmony/spotz/examples/vw/SparkVwCrossValidation.scala, line 29 [r4]](https://reviewable.io:443/reviews/eharmony/spotz/1#-KEcJzUrioawjTXX85mf:-KLzEhKar7bMnwU9xJpB:944238441) ([raw file](https://github.com/eharmony/spotz/blob/4e3806ec8c4f9f7dd80922635d58784558b44009/src/main/scala/com/eharmony/spotz/examples/vw/SparkVwCrossValidation.scala#L29)):_
<details><summary>

<i>Previously, jmorra (Jon Morra) wrote…</i></summary>



> Where do these numbers come from?
> </details>
> I arbitrarily made them up.  This example is a testbed to ensure certain functionality works, ie. the sampler was actually generating doubles between 0 and 20 uniformly.  I'll write test cases in the future.

---

_[src/main/scala/com/eharmony/spotz/optimizer/package.scala, line 4 [r4]](https://reviewable.io:443/reviews/eharmony/spotz/1#-KEcUFaJrT9As4cGjG_1:-KLzKg51BfvVinW2616Y:1248300125) ([raw file](https://github.com/eharmony/spotz/blob/4e3806ec8c4f9f7dd80922635d58784558b44009/src/main/scala/com/eharmony/spotz/optimizer/package.scala#L4)):_
<details><summary>

<i>Previously, jmorra (Jon Morra) wrote…</i></summary>



> Why is this necessary?
> </details>
> It doesn't need to be here.  At the time, I was looking for a type definition of a reducer but wasn't sure where it was defined in Scala / Spark so I defined my own.  Regardless, it's not necessary, as (T, T) => T suffices.  It's used after a batch of points are evaluated on the objective function, and the min or max out of those evaluations needs to be found.

---

_[src/main/scala/com/eharmony/spotz/util/RegexUtil.scala, line 6 [r4]](https://reviewable.io:443/reviews/eharmony/spotz/1#-KEcVLI319HsvbaAJDtQ:-KLzFyd3K6Z_L6nrS041:-993502096) ([raw file](https://github.com/eharmony/spotz/blob/4e3806ec8c4f9f7dd80922635d58784558b44009/src/main/scala/com/eharmony/spotz/util/RegexUtil.scala#L6)):_
<details><summary>

<i>Previously, jmorra (Jon Morra) wrote…</i></summary>



> Is it worthwhile to put the VW loss regex here too?
> </details>
> Possibly.  I wanted to keep the VW related stuff in its own package.

---

_[src/main/scala/com/eharmony/spotz/objective/vw/SparkVwCrossValidationObjective.scala, line 46 [r4]](https://reviewable.io:443/reviews/eharmony/spotz/1#-KEcKOxS2VmnCHH04ni8:-KLzGAUcfYvLsOBuQ8mW:-1510379395) ([raw file](https://github.com/eharmony/spotz/blob/4e3806ec8c4f9f7dd80922635d58784558b44009/src/main/scala/com/eharmony/spotz/objective/vw/SparkVwCrossValidationObjective.scala#L46)):_
<details><summary>

<i>Previously, jmorra (Jon Morra) wrote…</i></summary>



> This leaves the Source open.  It should be closed.
> </details>
> Good catch

---

_[src/main/scala/com/eharmony/spotz/objective/vw/SparkVwCrossValidationObjective.scala, line 50 [r4]](https://reviewable.io:443/reviews/eharmony/spotz/1#-KEcStbMTpO9KghCqMPb:-KLzGp-Zt9ayBSIOiFnd:395272812) ([raw file](https://github.com/eharmony/spotz/blob/4e3806ec8c4f9f7dd80922635d58784558b44009/src/main/scala/com/eharmony/spotz/objective/vw/SparkVwCrossValidationObjective.scala#L50)):_
<details><summary>

<i>Previously, jmorra (Jon Morra) wrote…</i></summary>



> Can this be done better using `groupBy`?
> </details>
> Not sure how it'd be applicable here.  The Map's type parameter could use some documentation though. It's not obvious what it means.

---

_[src/main/scala/com/eharmony/spotz/objective/vw/SparkVwCrossValidationObjective.scala, line 58 [r4]](https://reviewable.io:443/reviews/eharmony/spotz/1#-KEcTXl-0e1b5ZHueCMZ:-KLzD0bQw79ym-jhP_Sd:732898576) ([raw file](https://github.com/eharmony/spotz/blob/4e3806ec8c4f9f7dd80922635d58784558b44009/src/main/scala/com/eharmony/spotz/objective/vw/SparkVwCrossValidationObjective.scala#L58)):_
<details><summary>

<i>Previously, jmorra (Jon Morra) wrote…</i></summary>



> It seems like the code for this and testing is very similar, should this be a separate function?
> </details>
> Agreed, moved functionality so that it can be reused

---

_[src/main/scala/com/eharmony/spotz/objective/vw/SparkVwCrossValidationObjective.scala, line 108 [r4]](https://reviewable.io:443/reviews/eharmony/spotz/1#-KEcTrsXAbPAjq3-bg_e:-KLzDPGUn_WHGVKIbQir:1828909390) ([raw file](https://github.com/eharmony/spotz/blob/4e3806ec8c4f9f7dd80922635d58784558b44009/src/main/scala/com/eharmony/spotz/objective/vw/SparkVwCrossValidationObjective.scala#L108)):_
<details><summary>

<i>Previously, jmorra (Jon Morra) wrote…</i></summary>



> I assume in the future you will support a lot more options than just l?
> </details>
> Yes, this class was really just an experiment to see if the VW cross validation with cache files could even be implemented and working properly.  Happy to say it works.  This has been refactored since so that any hyper parameters in the Point object will be used.

---

_[src/main/scala/com/eharmony/spotz/optimizer/RandomSearch.scala, line 27 [r4]](https://reviewable.io:443/reviews/eharmony/spotz/1#-KEcULg2ARrE1Ti_gChK:-KLzHXtxvC0szWmGXiOJ:-1169944885) ([raw file](https://github.com/eharmony/spotz/blob/4e3806ec8c4f9f7dd80922635d58784558b44009/src/main/scala/com/eharmony/spotz/optimizer/RandomSearch.scala#L27)):_
<details><summary>

<i>Previously, jmorra (Jon Morra) wrote…</i></summary>



> I think you should expose this as a parameter even it has a default value in the constructor.
> </details>
> The seed here actually becomes irrelevant.  Since the sampling occurs on the executor, there is a need for the seed to be different on every executor.  If it is the same, every executor will generate the same numbers.  Currently, the seed is deterministically set to be the trial number.  There's probably a better way to do this, but the randomness is repeatable.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/eharmony/spotz/1)_

**Comment by vsuthichai** [comment]
Reviewed 3 of 24 files at r1, 2 of 2 files at r3, 2 of 12 files at r4, 19 of 32 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/eharmony/spotz/1)_

**Comment by vsuthichai** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[a discussion](https://reviewable.io:443/reviews/eharmony/spotz/1#-KD1F_pRY0s7FKLZTy64:-KLzNZy3om-ratMOmEzB:-1674809210) (no related file):_
<details><summary>

<i>Previously, vsuthichai (Victor Suthichai) wrote…</i></summary>



> Add unit tests
> </details>
> do it!

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/eharmony/spotz/1)_

**Pull request merged**
